<?php

namespace Site\MessageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ThreadMetadataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadMetadataRepository extends EntityRepository
{
}
