<?php

namespace Site\ActivityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleGradeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleGradeRepository extends EntityRepository
{
}
