<?php

namespace Site\TicketBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TicketTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketTicketRepository extends EntityRepository
{
}
