<?php

namespace Site\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ForumPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumPostRepository extends EntityRepository
{
}
